import Head from "next/head";
import Link from "next/link";
import React, { useContext, useEffect, useState } from "react";
import Footer from "./footer/Footer";
import { FaShoppingCart } from "react-icons/fa";
import { Store } from "@/utils/Store";
import { ToastContainer } from "react-toastify";
import { signOut, useSession } from "next-auth/react";
import "react-toastify/dist/ReactToastify.css";
import { Menu } from "@headlessui/react";

import Cookies from "js-cookie";

export default function Layout({ title, children }) {
  const [cartItemsCount, setCartItemsCount] = useState(0);
  const { state, dispatch } = useContext(Store);
  const { cart } = state;

  const { status, data: session } = useSession();

  useEffect(() => {
    setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
  }, [cart.cartItems]);

  function logoutClickHandler() {
    Cookies.remove("cart");
    dispatch({ type: "CART_RESET" });
    signOut({ callbackUrl: "/login" });
  }
  return (
    <>
      <Head>
        <title>{title ? title + "-Firdavs-Market" : "Firdavs-Market"}</title>
        <meta name="description" content="Generated by NEXTJS" />
      </Head>
      <ToastContainer position="bottom-center" limit={1} />
      <div className="flex min-h-screen flex-col justify-between">
        <header className="">
          <nav
            style={{ color: "#4cf2f5" }}
            className="flex bg-gray-900 h-16 px-4 justify-between items-center shadow-md  "
          >
            <Link
              style={{ fontSize: "22px" }}
              className="text-lg font-bold"
              href="/"
            >
              firdavs market
            </Link>
            <div className="flex">
              <Link
                // style={{
                //   border: "1px solid #4cf2f5",
                //   marginRight: "1rem",
                //   padding: "0 1rem",
                // }}
                className="font-bold hover:opacity-80"
                href="/cart"
              >
                <div
                  style={{
                    // border: "2px solid #4cf2f5 ",
                    // padding: "0.25rem",

                    marginRight: "2rem",
                    marginTop: "0.15rem",
                    textAlign: "center",
                    color: "white",

                    display: "flex",
                    justifyContent: "space-around",
                  }}
                >
                  <FaShoppingCart style={{ fontSize: "24px" }} />

                  <div>
                    {cartItemsCount > 0 && (
                      <span
                        style={{
                          background: "#4cf2f5",
                          borderRadius: "50%",
                          padding: "0 4px",
                          marginBottom: "4rem",
                          fontSize: "12px",
                          color: "black",
                        }}
                      >
                        {cartItemsCount}
                      </span>
                    )}
                  </div>
                </div>
              </Link>
              {status === "loading" ? (
                "Loading"
              ) : session?.user ? (
                <Menu as="div" className="relative  inline-block">
                  <Menu.Button className="text-white">
                    {session.user.name}
                  </Menu.Button>
                  <Menu.Items className="absolute transition ease-out duration-000 -right-4 w-56 origin-top-right shadow-lg">
                    {/* <Menu.Item>
                      <DropdownLink
                        className=" text-white mt-3  bg-gray-800  dropdown-link"
                        href="/profile"
                      >
                        Profile
                      </DropdownLink>
                    </Menu.Item> */}
                    {/* <Menu.Item>
                      <DropdownLink
                        className="dropdown-link text-white  bg-gray-800"
                        href="/order-history"
                      >
                        Order History
                      </DropdownLink>
                    </Menu.Item> */}
                    <Menu.Item>
                      <a
                        className="text- bg-gray-800  text-red-600 dropdown-link"
                        href="#"
                        onClick={logoutClickHandler}
                      >
                        Logout
                      </a>
                    </Menu.Item>
                  </Menu.Items>
                </Menu>
              ) : (
                <Link
                  style={{
                    border: "2px solid #4cf2f5",
                    padding: "0 1rem",
                    textAlign: "center",

                    color: "#4cf2f5",
                  }}
                  className="font-bold bg-gray-800 hover:opacity-80"
                  href="/login"
                >
                  Login
                </Link>
              )}
            </div>
          </nav>
        </header>
        <main>{children}</main>
        <footer>
          <Footer />
        </footer>
      </div>
    </>
  );
}
