import bcrypt from "bcryptjs";

const data = {
  users: [
    // {
    //   name: "Sam",
    //   email: "test@test.com",
    //   password: bcrypt.hashSync("123456789"),
    //   isAdmin: true,
    // },
    {
      name: "John",
      email: "john11@gmail.com",
      password: bcrypt.hashSync("987654321"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Boneless mutton(1kg)",
      slug: "boneless-lamb",
      image: "/image/lamb-boneless.jpg",
      price: "16900",
      rating: "4.5",
      description: "Very yummy and soft and good for shashlik",
      category: "meat",
      countInStock: 10,
    },
    {
      name: "Bone in Lamb(1kg)",
      slug: "bone-lamb",
      image: "/image/bone-2.jpg",
      price: "11900",
      rating: "4.6",
      description: "The flavor is tasty ",
      category: "meat",
      countInStock: 12,
    },
    {
      name: "Boneless beef (1kg)",
      slug: "beef-boneless",
      image: "/image/beef.jpg",
      price: "14900",
      rating: "4.5",
      description: "Feel the real taste ",
      category: "meat",
      countInStock: 8,
    },

    {
      name: "Lamb neck (1kg)",
      slug: "lamb-neck",
      image: "/image/neck.jpg",
      price: "10900",
      rating: "4.5",
      description: "Best option for soup stuff",
      category: "meat",
      countInStock: 20,
    },
    {
      name: "Beef mince (1kg)",
      slug: "ground-beef",
      image: "/image/ground.jpg",
      price: "14900",
      rating: "4.8",
      description: "Neither fatty nor bony ",
      category: "meat",
      countInStock: 15,
    },

    {
      name: "Beef trotters (1kg)",
      slug: "trotter-beef",
      image: "/image/trotter.jpg",
      price: "7900",
      rating: "4.3",
      description: "100% halal trotters ",
      category: "meat",
      countInStock: 8,
    },
    {
      name: "Lamb fat (1kg)",
      slug: "lamb-fat",
      image: "/image/fat.jfif",
      price: "6900",
      rating: "4.4",
      description: "Immune system booster and viral desease protector ",
      category: "meat",
      countInStock: 15,
    },
    {
      name: "Whole chicken (1kg)",
      slug: "whole-chicken",
      image: "/image/chicken-whole.jpg",
      price: "5900",
      rating: "4.7",
      description: "Highr versatility- can be used multinational cuisines ",
      category: "chicken",
      countInStock: 25,
    },
    {
      name: "Chicken leg (2kg)",
      slug: "chicken-leg",
      image: "/image/chicken-breast.jpg",
      price: "12900",
      rating: "4.8",
      description: "Neither fatty nor bony ",
      category: "chicken",
      countInStock: 18,
    },
    {
      name: "Chicken breast (2kg)",
      slug: "chicken-breast",
      image: "/image/chicken-breast.jpg",
      price: "13900",
      rating: "4.9",
      description: "Soft and delicious ",
      category: "chicken",
      countInStock: 9,
    },
    {
      name: "Basmati rice (1kg)",
      slug: "basmati-rice",
      image: "/image/basmati.jpg",
      price: "6900",
      rating: "4.9",
      description: "Sella basmati rice for biryani and plov ",
      category: "rice",
      countInStock: 9,
    },
    {
      name: "Russian jam",
      slug: "jam",
      image: "/image/jam-r.jfif",
      price: "6900",
      rating: "4.5",
      description: "Russian jam very delicious ",
      category: "other",
      countInStock: 19,
    },
    {
      name: "Cucumber pickles",
      slug: "zulya-cucumber",
      image: "/image/zulya-8500.jpg",
      price: "8500",
      rating: "4.6",
      description: "Pickles zulya baraka ",
      category: "pickle",
      countInStock: 22,
    },
    {
      name: "Berrak Cucumber pickles (1.5l)",
      slug: "berrak-c",
      image: "/image/berrak-c.png",
      price: "9500",
      rating: "4.8",
      description: "Great taste of cucumber pickle from Turkey ",
      category: "pickle",
      countInStock: 14,
    },
    {
      name: "Mixed pickles(1.5l)",
      slug: "mixed-b",
      image: "/image/mixed-b.jfif",
      price: "9500",
      rating: "4.5",
      description: "Turkish mixed pickles. Not sweet ",
      category: "pickle",
      countInStock: 19,
    },
    {
      name: "Salted almonds (160 gr)",
      slug: "salted-almond",
      image: "/image/pista.jpg",
      price: "4500",
      rating: "4.3",
      description: "Pakistani salted almonds  ",
      category: "other",
      countInStock: 29,
    },
    {
      name: "Divella Macaron (0.5kg)",
      slug: "divella-pasta",
      image: "/image/divella.jpg",
      price: "2500",
      rating: "4.4",
      description: "Product of Italy, feel the taste of italian macaron ",
      category: "other",
      countInStock: 19,
    },
    {
      name: "Dates Crown Khalas (1kg)",
      slug: "date-crown",
      image: "/image/date-7000.jfif",
      price: "6900",
      rating: "4.6",
      description: "Premium Emirates Dates ",
      category: "date",
      countInStock: 17,
    },
    {
      name: "Dates Royal (1kg)",
      slug: "date-royal",
      image: "/image/royal.jpg",
      price: "10900",
      rating: "4.7",
      description: " Emirates Dates Deglet Nour  ",
      category: "date",
      countInStock: 17,
    },
    {
      name: "Dates Royal Pitted (1kg)",
      slug: "seedless-dates",
      image: "/image/oliy.jpg",
      price: "11500",
      rating: "4.9",
      description: "Seedless date palm ",
      category: "date",
      countInStock: 17,
    },
    {
      name: "Chocolate nutella",
      slug: "choco-nutella",
      image: "/image/nutella.jpg",
      price: "12500",
      rating: "4.8",
      description: "Enjoy the real chocolate taste ",
      category: "choco",
      countInStock: 16,
    },
    {
      name: "Cooking oil (1l)",
      slug: "cooking-oil",
      image: "/image/oil-1.jpg",
      price: "5500",
      rating: "4.8",
      description: "Russian cooking oil, 1 litr, halal ",
      category: "oil",
      countInStock: 18,
    },
    {
      name: "Cooking oil (3l)",
      slug: "cooking-oil-2",
      image: "/image/oil-3.jpg",
      price: "15500",
      rating: "4.7",
      description: "Russian cooking oil, 3 litr, halal ",
      category: "oil",
      countInStock: 11,
    },
    {
      name: "Cooking oil (5l)",
      slug: "cooking-oil-5",
      image: "/image/oil-5.jpeg",
      price: "5500",
      rating: "4.8",
      description: "Russian cooking oil, 5 litr, halal ",
      category: "oil",
      countInStock: 18,
    },
    {
      name: "Green peas",
      slug: "green-peas",
      image: "/image/green.jpg",
      price: "4500",
      rating: "4.8",
      description: "Garden peas. in water, sugar and salt added ",
      category: "other",
      countInStock: 18,
    },
    {
      name: "Mayonnaise",
      slug: "mayonnaise-egg",
      image: "/image/mayonez.jpg",
      price: "8500",
      rating: "4.3",
      description: "Mayonnaise with quail eggs ",
      category: "other",
      countInStock: 0,
    },
    {
      name: "Tomato paste",
      slug: "tomato-paste",
      image: "/image/sera.jpeg",
      price: "6500",
      rating: "4.8",
      description:
        "Sera tomato paste. Double concentrate, no salt added, halal ",
      category: "other",
      countInStock: 18,
    },
    {
      name: "Eggplant caviar",
      slug: "eggplant-caviar",
      image: "/image/ikra.jpg",
      price: "5000",
      rating: "4.7",
      description: "Eggplant spread ikra russian style ",
      category: "other",
      countInStock: 15,
    },
    {
      name: "Vital black tea",
      slug: "tea-b",
      image: "/image/vital.png",
      price: "8900",
      rating: "4.7",
      description: "uncommon feeling with vital black tea",
      category: "other",
      countInStock: 15,
    },
    {
      name: "Truffle chocolate",
      slug: "truffle-ch",
      image: "/image/truffle.jpg",
      price: "8500",
      rating: "4.5",
      description: "Turkish chocolate, halal",
      category: "other",
      countInStock: 12,
    },
    {
      name: "Green Tea",
      slug: "green-tea",
      image: "/image/toza.jpg",
      price: "8500",
      rating: "4.5",
      description: "Uzbekistan green tea (110 / 95 both available)",
      category: "other",
      countInStock: 11,
    },
    {
      name: "Sunflower seeds",
      slug: "seeds-s",
      image: "/image/jin-250.jpg",
      price: "4900",
      rating: "4.7",
      description: "Russian salted sunflower seeds",
      category: "other",
      countInStock: 11,
    },
    {
      name: "Sunflower seeds",
      slug: "seeds-china",
      image: "/image/xitoy-q.jpg",
      price: "3500",
      rating: "4.1",
      description: "Chinese salted sunflower seeds",
      category: "other",
      countInStock: 11,
    },
    {
      name: "Sunflower seeds",
      slug: "seeds-un",
      image: "/image/xitoy-k.jpg",
      price: "14900",
      rating: "4.2",
      description: "Chinese unsalted sunflower seeds",
      category: "other",
      countInStock: 11,
    },
    {
      name: "Honey (100%)",
      slug: "honey-100",
      image: "/image/honey.jpeg",
      price: "14900",
      rating: "4.5",
      description: "Real honey from Argentina",
      category: "other",
      countInStock: 5,
    },
    {
      name: "Condensed Milk",
      slug: "condenced-m",
      image: "/image/milk.jpg",
      price: "4500",
      rating: "4.6",
      description: "Natural condensed milk from Russia",
      category: "other",
      countInStock: 15,
    },

    {
      name: "Wafers Korovka",
      slug: "waf-ko",
      image: "/image/korovka.jpg",
      price: "3900",
      rating: "4.7",
      description: "wafers with cocoa chocolate filling, sweet snack",
      category: "other",
      countInStock: 5,
    },
    {
      name: "Milka Chocolate",
      slug: "milka-choco",
      image: "/image/milky.jpg",
      price: "2900",
      rating: "4.7",
      description:
        "Crafted with chocolate made with milk sourced from the Swiss Alps",
      category: "other",
      countInStock: 5,
    },
  ],
};
export default data;
